language: scala
sudo: false
jdk: oraclejdk8
scala:
    - 2.10.7
    - 2.11.12
    - 2.12.4
    - 2.13.0-M2

matrix:
  include:
  - env: SCALA_NATIVE
    sudo: required
    scala: 2.11.12
    dist: trusty
    before_install:
    - curl https://raw.githubusercontent.com/scala-native/scala-native/0f69c875d2cb2/bin/travis_setup.sh | bash -x
    script:
    - sbt protobufRuntimeScalaNative/test "show protobufRuntimeScalaNative/nativeMissingDependencies"
