language: scala
sudo: false
jdk: oraclejdk9
scala:
    - 2.10.7
    - 2.11.12
    - 2.12.10
    - 2.13.1

matrix:
  include:
  - env: SCALA_NATIVE
    sudo: required
    scala: 2.11.12
    dist: trusty
    before_install:
    - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
    script:
    - sbt protobufRuntimeScalaNative/test
